### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by EdBSTU** [AlexeyParfimovich/M-ND2-Homework#4]
Будьте внимательны с форматированием, если пишется комментарий то каждая его строка должна быть как и все, это не критично, но просто на будущее, так как соответствие единообразия как стиля так и кода, очень показывает высокий уровень :) 

![image](https://user-images.githubusercontent.com/21379856/141350517-493e359b-a417-4be3-bbea-7f91e2023ad2.png)

https://github.com/AlexeyParfimovich/M-ND2-Homework/blob/428ddf59564b4f5372a970069403b0ad0fd2c114/Lesson02/ConsoleApp1/Program.cs#L10

**Comment by AlexeyParfimovich** [comment]
My fault, I have not checked how the indents are displayed on the github. In VS, all comment lines look the same. Thank you for bringing this issue to my attention.
